###Register

POST   http://localhost:3000/api/v1/auth/register

{
    "username":"marko",
    "name":"marko efendi",
    "email":"marko@mail.com",
    "password":"password",
    "bio":"lajang",
    "avatar":"marko.jpeg"

}

###find all users
GET http://localhost:3000/api/v1/auth/register